apiVersion: v2
name: qbittorrent-nox
description: A Helm chart for Headless qBittorrent

type: application

version: 0.1.0

appVersion: "4.5.0"

icon: https://fr.wikipedia.org/wiki/QBittorrent#/media/Fichier:New_qBittorrent_Logo.svg