apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent-nox.fullname" . }}
  labels:
    {{- include "qbittorrent-nox.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "qbittorrent-nox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrent-nox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent-nox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - qbittorrent-nox
        ports:
        - name: webui
          containerPort: {{ .Values.serviceWebUI.port }}
          protocol: TCP
        - name: bt-listener
          containerPort: {{ .Values.serviceBTListener.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config
          mountPath: /root/.config/qBittorrent/qBittorrent.conf
          subPath: qBittorrent.conf
        #- name: downloads
        #  mountPath: /Downloads
        #  subPath: qbittorrent-downloads
        #- name: downloads
        #  mountPath: /root/.local/share/qBittorrent/BT_backup
        #  subPath: qbittorrent-torrents
      volumes:
      - name: config
        configMap:
          name: {{ include "qbittorrent-nox.fullname" . }}
          items:
          - key: qBittorrent.conf
            path: qBittorrent.conf
      #- name: downloads
      #  persistentVolumeClaim:
      #    claimName: qbittorrent-downloads
      #    #readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
